# -*- coding: utf-8 -*-
"""NLP project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFUy88guTXfs760zYTHf8j8INNVDIZJt
"""

pip install transformers datasets torch accelerate sentencepiece

pip install opencv-python

!pip install evaluate

import torch
import pandas as pd
from datasets import load_dataset
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast, Trainer, TrainingArguments, DataCollatorForSeq2Seq

# ✅ Load tokenizer and model
model_name = "facebook/mbart-large-50"
tokenizer = MBart50TokenizerFast.from_pretrained(model_name)
model = MBartForConditionalGeneration.from_pretrained(model_name)

# ✅ Set language (Use 'mr_IN' for Marathi)
tokenizer.src_lang = "mr_IN"
tokenizer.tgt_lang = "mr_IN"

print("✅ Tokenizer and model loaded successfully!")

# ✅ Load dataset efficiently
data_files = {"train": "/content/marathi_output_train (3).csv", "test": "/content/marathi_output_test.csv"}
dataset = load_dataset("csv", data_files=data_files)

# ✅ Tokenization function
def preprocess_function(examples):
    model_inputs = tokenizer(
        examples["Text"],
        max_length=512,
        truncation=True,
        padding="max_length"
    )
    labels = tokenizer(
        examples["Summary"],
        max_length=128,
        truncation=True,
        padding="max_length"
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# ✅ Apply tokenization
tokenized_datasets = dataset.map(preprocess_function, batched=True, remove_columns=["Title", "Summary", "Text"])

# ✅ Move model to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# ✅ Training arguments (Optimized for GPU)
training_args = TrainingArguments(
    output_dir="./mbart_marathi_summarization",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=5,
    logging_dir="./logs",
    logging_steps=10,  # ✅ Log every 10 steps
    report_to="none",
    save_steps=1000,
    load_best_model_at_end=True,
    push_to_hub=False,
    fp16=True,  # ✅ Enable FP16 for faster GPU training
    disable_tqdm=False,  # ✅ Ensure progress bar is visible
)

# ✅ Data collator
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

# ✅ Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

# ✅ Train the model on GPU
if __name__ == "__main__":
    print("🔥 Training started on GPU...")
    train_results = trainer.train()
    print("✅ Training completed!")

    # ✅ Print training metrics
    print(train_results)

    # ✅ Evaluate the model
    eval_results = trainer.evaluate()
    print(f"📊 Evaluation results:\n{eval_results}")

    # ✅ Save trained model
    model.save_pretrained("./mbart_marathi_summarization")
    tokenizer.save_pretrained("./mbart_marathi_summarization")
    print("📁 Model and tokenizer saved successfully!")

from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

# Load trained model
model_name = "/content/mbart_marathi_summarization"
tokenizer = MBart50TokenizerFast.from_pretrained(model_name)
model = MBartForConditionalGeneration.from_pretrained(model_name).to("cuda")

# Input text for summarization
input_text = "2014 मध्ये औरंगाबाद मध्य आणि मुंबईतील भायखळा या दोन मतदारसंघातून एमआयएमचे आमदार निवडून आले होते. मात्र, यंदाच्या म्हणजे 2019 च्या विधानसभा निवडणुकीत एमआयएमनं या दोन्ही जागा गमावल्या आहेत. मात्र, एमआयएमची आमदारसंख्या दोनच राहिली आहे. कारण धुळे शहर आणि मालेगाव मध्य या दोन जागा जिंकण्यात एमआयएमला यश मिळालं आहे. धुळे शहर मतदारसंघातून फारूक शाह तर मालेगाव मध्य मतदारसंघातून मुफ्ती मोहम्मद इस्माईल जिंकले आहेत. यंदा उत्तर महाराष्ट्रात कोण किती जागा जिंकलं? औरंगाबाद मध्य आणि मुंबईतील भायखळा या दोन मतदारसंघातून 2014 साली एमआयएमचे आमदार जिंकले होते. ही दोन्ही ठिकाणं मुस्लीमबहुल लोकसंख्या असलेली आहेत. मात्र, यंदा जिंकलेल्या मालेगाव मध्य वगळल्यास धुळे शहरात निर्णायक मुस्लिम मतं नाहीत. त्यामुळे धुळे शहरात एमआयएमनं कशी बाजी मारली आणि कोणती समीकरणं कामी आली, याचा आढावा बीबीसी मराठीनं घेतला आहे. धुळे शहरात एमआयएमचा विजय कसा झाला? धुळे महापालिका निवडणुकीपासूनच भाजपचे विद्यमान आमदार अनिल गोटे पक्षावर नाराज होते. त्यामुळं ते धुळे शहरातून अपक्ष लढले. काँग्रेस-राष्ट्रवादीनं इथं उमेदवार न देता अनिल गोटेंना पाठिंबा दिला होता. आघाडीनं गोटेंना पाठिंबा दिल्यानं राष्ट्रवादीचे माजी आमदार राजवर्धन कदमबांडे नाराज झाले आणि अपक्ष म्हणून रिंगणात उतरले. त्यात शिवसेनेनंही हिलाल लाला माळींच्या रूपानं उमेदवार दिला होता. धुळे शहर मतदारसंघात मुस्लिमांची संख्या लक्षणीय आहे. त्यामुळं एमआयएमनंही या मतदारसंघात लक्ष देत फारूक शाह यांना रिंगणात उतरवलं होतं. फारूक शाह धुळे शहर मतदारसंघाचा गेल्या दोन दशकांचा इतिहास पाहता हा मतदारसंघ 1999 सालापासून आलटून-पालटून अनिल गोटे आणि राजवर्धन कमदबांडे यांच्याकडेच राहिला आहे. 1995 आणि 2004 अशा दोनवेळा राजवर्धन कदमबांडे तर 1999, 2009 आणि 2014 अशा तीनवेळा अनिल गोटे इथून विजयी झाले आहेत. गेली दोन दशकं आलटून-पालटून धुळे शहराचं विधानसभेत प्रतिनिधित्व करणाऱ्या अनिल गोटे आणि राजवर्धन कदमबांडे यांना बाजूला सारत इथल्या जनतेनं एमआयएमचे फारूक शाह यांना निवडलंय. उत्तर महाराष्ट्रातील वरिष्ठ पत्रकार मिलिंद सजगुरे सांगतात"

# Tokenize input
inputs = tokenizer(input_text, return_tensors="pt", truncation=True).to("cuda")

# Generate summary
summary_ids = model.generate(
    **inputs,
    max_length=128,
    num_beams=5,
    early_stopping=True
)

summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Generated Summary:", summary_text)

pip install datasets rouge_score

from transformers import MBartForConditionalGeneration, MBart50TokenizerFast
import torch

# Load fine-tuned model
model_path = "/content/mbart_marathi_summarization"  # Update this path if needed
tokenizer = MBart50TokenizerFast.from_pretrained(model_path)
model = MBartForConditionalGeneration.from_pretrained(model_path).to("cuda")

# Set tokenizer source language to Marathi
tokenizer.src_lang = "mr_IN"

import pandas as pd

# Load test dataset
test_data_path = "/content/marathi_output_test.csv"  # Update path if needed
df = pd.read_csv(test_data_path)

# Extract text and corresponding reference summaries
texts = df["Text"].tolist()
references = df["Summary"].tolist()

print(f"Loaded {len(texts)} test samples.")

def generate_summary(text):
    inputs = tokenizer(text, return_tensors="pt", max_length=512, truncation=True).to("cuda")

    # Force the output to Marathi
    forced_bos_token_id = tokenizer.lang_code_to_id["mr_IN"]

    summary_ids = model.generate(
        **inputs,
        max_length=100,
        num_beams=5,
        forced_bos_token_id=forced_bos_token_id
    )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# Generate summaries for all test samples
predictions = [generate_summary(text) for text in texts]

# Print a few examples
for i in range(3):  # Show first 3 summaries
    print(f"\nOriginal: {texts[i]}")
    print(f"Reference Summary: {references[i]}")
    print(f"Generated Summary: {predictions[i]}")

!pip install evaluate  # Install the new evaluate library

from evaluate import load

# Load ROUGE metric
rouge = load("rouge")

# Compute ROUGE scores
rouge_scores = rouge.compute(predictions=predictions, references=references)

# Print formatted results
for key, value in rouge_scores.items():
    print(f"{key}: {value:.4f}")

import shutil

# Path where your model is saved (update if needed)
model_path = "/content/mbart_marathi_summarization"

# Create a zip file of the model directory
shutil.make_archive("mbart_marathi_summarization", 'zip', model_path)

print("Model zipped successfully!")